---

- name: install apt requirements
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - git
    - unzip

- name: Download
  git:
    repo: "{{ wallabag_git_url }}"
    version: "{{ wallabag_version }}"
    dest: /opt/wallabag
    force: yes
  register: wallabag_download
  notify: restart php

- name: Configure
  template:
    src: opt/wallabag/app/config/parameters.yml.j2
    dest: /opt/wallabag/app/config/parameters.yml
    owner: wallabag
    group: wallabag

- name: Install php dependencies
  composer:
    command: install
    working_dir: /opt/wallabag
    prefer_dist: True
    no_dev: False
    optimize_autoloader: True
  register: wallabag_install

- name: install
  shell: yes no | /opt/wallabag/bin/console wallabag:install -e prod
  when: wallabag_download | changed

- name: check users
  command: bin/console wallabag:user:list
  args:
    chdir: /opt/wallabag
  register: wallabag_users
  changed_when: False

- name: create admin user
  no_log: True
  command: "bin/console fos:user:create {{ wallabag_admin }} {{ wallabag_admin_email }} {{ wallabag_admin_password }} --super-admin"
  args:
    chdir: /opt/wallabag
  when: "wallabag_admin not in wallabag_users.stdout"

- name: deactivate wallabag user
  command: "bin/console fos:user:deactivate wallabag"
  args:
    chdir: /opt/wallabag
  when: wallabag_users.stdout | match("wallabag ( *)no")

- name: demote wallabag user
  command: "bin/console fos:user:demote wallabag --super"
  args:
    chdir: /opt/wallabag
  when: wallabag_users.stdout | match("wallabag ( *)(no|yes)( *)no")

- name: change wallabag user password
  no_log: True
  command: "bin/console fos:user:change-password wallabag lookup('password')"
  args:
    chdir: /opt/wallabag
  when: wallabag_install | changed

- name: permissions
  command: chown -R wallabag:wallabag /opt/wallabag/web /opt/wallabag/var /opt/wallabag/bin /opt/wallabag/app/config /opt/wallabag/vendor
  when: wallabag_download | changed
